import Head from "next/head";
import LeftSideBar from "../components/Home/LeftSideBar";
import MiddleLeftBar from "../components/Home/MiddleLeftBar";
import MiddleRightBar from "../components/Home/MiddleRightBar";
import RightSideBar from "../components/Home/RightSideBar";
import Navigation from "../components/Share/Navigation";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTv } from '@fortawesome/free-solid-svg-icons'


const element = <FontAwesomeIcon icon={faTv} />


export default function Home() {
  return (
    <div className="bg-neutral-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation></Navigation>
      <div className="w-full">
        <div className="grid grid-cols-12">
          <div className="col-span-2">
            <LeftSideBar></LeftSideBar>
          </div>
          <div className="col-span-8 w-4/5 mx-auto">
            <div className="grid gap-5 grid-cols-12">
              <div className="col-span-8">
                <MiddleLeftBar></MiddleLeftBar>
              </div>
              <div className="col-span-4">
                <MiddleRightBar></MiddleRightBar>
              </div>
            </div>
          </div>
          <div className="col-span-2">
            <RightSideBar></RightSideBar>
          </div>
        </div>
      </div>
    </div>
  );
}
